#!/bin/sh
#############################################################################
##
## Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
## Contact: http://www.qt-project.org/
##
## $QT_BEGIN_LICENSE:LGPL$
## GNU Lesser General Public License Usage
## This file may be used under the terms of the GNU Lesser General Public
## License version 2.1 as published by the Free Software Foundation and
## appearing in the file LICENSE.LGPL included in the packaging of this
## file. Please review the following information to ensure the GNU Lesser
## General Public License version 2.1 requirements will be met:
## http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html.
##
## In addition, as a special exception, Nokia gives you certain additional
## rights. These rights are described in the Nokia Qt LGPL Exception
## version 1.1, included in the file LGPL_EXCEPTION.txt in this package.
##
## GNU General Public License Usage
## Alternatively, this file may be used under the terms of the GNU General
## Public License version 3.0 as published by the Free Software Foundation
## and appearing in the file LICENSE.GPL included in the packaging of this
## file. Please review the following information to ensure the GNU General
## Public License version 3.0 requirements will be met:
## http://www.gnu.org/copyleft/gpl.html.
##
## Other Usage
## Alternatively, this file may be used in accordance with the terms and
## conditions contained in a signed written agreement between you and Nokia.
##
##
##
##
##
##
## $QT_END_LICENSE$
##
#############################################################################

# This script, if called from an ifup hook, will force the host name to be
# set to the value from DHCP.
#
# NetworkManager is capable of doing this on its own, but it decides not to
# if other hostnames are already present in /etc/hosts and/or /etc/hostname
# (the exact behavior is unclear). This script overrides NM's own behavior
# to ensure the hostname is _always_ set. Of course, this only makes sense
# in a trusted DHCP environment.

scriptname="$(basename $0)"

if test -n "$DHCP4_HOST_NAME"; then
    hostname "$DHCP4_HOST_NAME" 2>&1
    echo "set hostname to $DHCP4_HOST_NAME"
else
    echo "warning: DHCP4_HOST_NAME is not set"
fi 2>&1 | logger -t "$scriptname"

